"""empty message

Revision ID: 4daaaa5413c6
Revises: b474d67ddaa0
Create Date: 2018-10-25 11:36:47.364142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4daaaa5413c6'
down_revision = 'b474d67ddaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salarys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.String(length=10), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salarys_employee'), 'salarys', ['employee'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salarys_employee'), table_name='salarys')
    op.drop_table('salarys')
    # ### end Alembic commands ###
